baseURL = "http://example.org/"
languageCode = "en-us"
title = "Max Redmond"
theme = "resume"
publishDir = "docs"

[params]
    firstName = "Max"
    lastName = "Redmond"
    address = "Richmond, VA"
    phone = "1-555-555-1234"
    contactNote = "Software Developer"
    profileImage = "img/profile.png"
    email = "contact@maxredmond.info"
    description = "Software Developer with experience in backend web developement, the pubic cloud, and embedded stuff"
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = false
    showExperience = true
    showEducation = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/max-redmond-26ab9764/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/athulus/"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/athulus"
    icon = "key"
